### ISSUE TITLE
Pass parameterOrder to Swagger extension

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/google-discovery-to-swagger#1]
This helps organize parameters in an API console.  We should create an x-parameterOrder field in Swagger

**Comment by IvanGoncharov** [comment]
Google use parameter order because the put parameters in object and so JSON doesn't preserve they order. That's why they add additional `parameterOrder` field.
Contrary to this Swagger put parameters into array which preserve order.
In my converter I sort parameters based on Google's `parameterOrder`.

**Comment by IvanGoncharov** [comment]
@bobby-brennan, I checked code and you right.
I made typo and right now sorting based on `parameterOrder` is broken.

**Comment by bobby-brennan** [comment]
That makes sense, thanks

Bobby Brennan
bobby.brennan@gmail.com

**Comment by IvanGoncharov** [comment]
I already updated APIs-guru/api-models.
